CREATE DATABASE TecnoImportDB;
USE TecnoImportDB;
DROP DATABASE  TecnoImportDB;
CREATE TABLE Login (
	 IDUSUARIO INT,
     USUARIO   VARCHAR(30),
	 CLAVE 	   VARCHAR(30),
     TIPO 	   VARCHAR(1) # 'g' gerente 'v' vendedor 'j' jefeBodega
);

CREATE TABLE Locall(
	IDLOCAL 	INT PRIMARY KEY,
    DIRECCION  	VARCHAR(50),
    CIUDAD		VARCHAR(50),
    PAIS		VARCHAR(50),
	esMATRIZ	VARCHAR(1)		# m= es Matriz  l = es Local 
);

CREATE TABLE Producto(
	IDPRODUCTO 	INT PRIMARY KEY,
    NOMBRE 		VARCHAR(50),
    CANTIDADSTOCK INT,
    DESCRIPCION VARCHAR(200),
    CATEGORIA 	VARCHAR(50),
    PRECIOUNIT  INT
);
#DROP TABLE Producto;
#DROP TABLE INVENTARIO;
CREATE TABLE Bodega(
	IDBODEGA	INT PRIMARY KEY,
    DIRECCION   VARCHAR(50),
    CIUDAD		VARCHAR(50),
    PAIS 		VARCHAR(50)
);

CREATE TABLE Inventario(
    IDPRODUCTO 			INT,
    IDLOCAL 			INT,
    IDBODEGA 			INT,
    CANTIDADUBICACION 	INT,
    NOMBRE 				VARCHAR(50),
    FOREIGN KEY (IDLOCAL) REFERENCES Locall(IDLOCAL),
    FOREIGN KEY (IDBODEGA) REFERENCES Bodega(IDBODEGA),
    FOREIGN KEY (IDPRODUCTO) REFERENCES Producto(IDPRODUCTO)
);



CREATE TABLE Vendedor (
	IDVENDEDOR  VARCHAR(20) PRIMARY KEY,  #cedula
    NOMBRE 		VARCHAR(30),
    APELLIDO 	VARCHAR(30),
    TIPO 		VARCHAR(1),
    PERMISOS 	VARCHAR(1) 
);
CREATE TABLE JefeDeBodega(
	IDJEFEBODEGA VARCHAR(20) PRIMARY KEY, #cedula
	NOMBRE 		VARCHAR(30),
    APELLIDO 	VARCHAR(30),
    IDBODEGA	INT,
    FOREIGN KEY(IDBODEGA) REFERENCES Bodega(IDBODEGA)
);

CREATE TABLE Cliente(
	IDCLIENTE 	VARCHAR(20) PRIMARY KEY, #cedula
    NOMBRE 		VARCHAR(30),
    APELLIDO 	VARCHAR(30),
    CUENTABANCARIA VARCHAR(30),
    DIRECCION 	VARCHAR(30)
);

CREATE TABLE Gerente(
	IDGERENTE 	VARCHAR(20) PRIMARY KEY,  #cedula
    NOMBRE 		VARCHAR(30),
    APELLIDO 	VARCHAR(30)
);
CREATE TABLE Repartidor(
	IDREPARTIDOR 	VARCHAR(20) PRIMARY KEY,  #cedula
    NOMBRE 			VARCHAR(30),
    APELLIDO 		VARCHAR(30),
    CANTIDADENTREGA INT #Se incrementara por cada entrega que se le asigne
);



# <----------------------------DATA--------------------------->

INSERT INTO Login (IDUSUARIO,USUARIO,CLAVE,TIPO)
VALUES(111,'chjoguer','sistemas1','g'),
	  (222,'josepe','cambio','v'),
	  (333,'benjikrol','ben100','j'),
	  (444,'miglml','ambition','v');
      
INSERT INTO Locall(IDLOCAL,DIRECCION,CIUDAD,PAIS,esMATRIZ)
VALUES(1,'VIA A DUALE KM 5','Guayaquil','Ecuador','l'),
	  (2,'AV/ BOMBERO KM 7','Guayaquil','Ecuador','m');
      
INSERT INTO Bodega(IDBODEGA,DIRECCION,CIUDAD,PAIS)
VALUES(1,'VIA A Samborondon KM 5','Guayaquil','Ecuador');
#INSERT INTO JefeDeBodega(IDJEFEBODEGA,NOMBRE,APELLIDO,IDBODEGA)
#VALUES('09991','Benjamin','Krol',1);

INSERT INTO Producto(IDPRODUCTO,NOMBRE,CANTIDADSTOCK ,DESCRIPCION,CATEGORIA,PRECIOUNIT)
VALUES(1,'LCD 32',200,'NUEVO','ENTRETENIMIENTO',400),
	   (2,'LCD 55',200,'NUEVO','ENTRETENIMIENTO',600),
	   (3,'SMART TV 32',200,'NUEVO','ENTRETENIMIENTO',600),
	   (4,'PS4',25,'NUEVO','ENTRETENIMIENTO',350),
	   (5,'XBOX',25,'NUEVO','ENTRETENIMIENTO',300);


INSERT INTO Inventario(IDPRODUCTO,IDLOCAL,IDBODEGA,CANTIDADUBICACION,NOMBRE)
VALUES(1,1,1,100,'LCD 32'),
		(2,2,1,50,'LCD 55'),
		(3,1,1,100,'SMART TV 55');
        
        



select * from JefeDeBodega j , Bodega b WHERE j.IDBODEGA = b.IDBODEGA; 


select * from Inventario;
# <----------------------------STORED PROCEDURES-------------------------->
DELIMITER //
CREATE PROCEDURE login(IN USERNICK VARCHAR(20), IN PASS VARCHAR(20), OUT id INTEGER, OUT t VARCHAR(1))
  BEGIN
    SET id := 0;
    IF (SELECT count(*) FROM login WHERE USUARIO =  USERNICK AND CLAVE = pass) = 1
    THEN
      SET id := (SELECT login.IDUSUARIO FROM login WHERE USUARIO = USERNICK  AND CLAVE = pass);
      SET t := (SELECT login.TIPO FROM login WHERE USUARIO = USERNICK AND CLAVE = pass);
    END IF;
  END //	
 
CREATE PROCEDURE INVENTARIO()
	BEGIN
		SELECT i.NOMBRE,p.CANTIDADSTOCK,p.PRECIOUNIT,i.CANTIDADUBICACION,b.IDBODEGA,l.IDLOCAL,l.esMAtriz
        FROM Inventario i, Producto p , Bodega b, Locall l WHERE i.IDPRODUCTO = p.IDPRODUCTO 
        AND i.IDBODEGA=b.IDBODEGA AND i.IDLOCAL=l.IDLOCAL;
    END//
set t =' ';
call login('josepe','cambio',@id,@t);
select @id ,@t
select * from login

#--------PROCEDURES DE PRODUCTOS
CREATE PROCEDURE UPDATESTOCK(IN IDPRODUCT INT, IN NUEVOSTOCK INT)
	BEGIN
		UPDATE PRODUCTO SET CANTIDADSTOCK = NUEVOSTOCK WHERE IDPRODUCTO = IDPRODUCT;
    END//

CREATE PROCEDURE UPDATEPRECIO(IN IDPRODUCT INT , IN NUEVOPRECIO INT)
	BEGIN
		UPDATE PRODUCTO SET  PRECIOUNIT= NUEVOPRECIO WHERE IDPRODUCTO = IDPRODUCT;
    END//
    
CREATE PROCEDURE GETPROCUTOXDESCRIPCION(IN DESCRIP VARCHAR(200))
	BEGIN
		SELECT p.NOMBRE, p.CANTIDADSTOCK , p.DESCRIPCION , p.CATEGORIA , p.PRECIOUNIT 
		FROM PRODUCTO p 
        WHERE p.DESCRIPCION = DESCRIP;
	END//
    
CREATE PROCEDURE GETPROCUTOXCATEGORIA(IN CATEG VARCHAR(200))
	BEGIN
		SELECT  p.NOMBRE, p.CANTIDADSTOCK , p.DESCRIPCION , p.CATEGORIA , p.PRECIOUNIT 
		FROM PRODUCTO p WHERE p.CATEGORIA = CATEG;
    END//
    
CREATE PROCEDURE GETPROCUTOXNOMBRE(IN NOMBRE VARCHAR(200))
	BEGIN
		SELECT  p.NOMBRE, p.CANTIDADSTOCK , p.DESCRIPCION , p.CATEGORIA , p.PRECIOUNIT 
		FROM PRODUCTO p WHERE p.NOMBRE = NOMBRE;
	END//


# <----------------------------VIEWS-------------------------->


